- physx-sys/Cargo.toml
- physx-sys/build.rs
The [`build-helper`](https://crates.io/crates/build-helper) crate and repo has not been updated in 2 years and looks abandoned, and we have a long running PR for it (https://github.com/DanielKeep/rust-build-helper/pull/2) with some dependency updates that haven't been merged in nor any communication about.
So let's just remove the dependency and use explicit Cargo env vars and `prinln` instructions instead, easy enough.
> Remove build-helper dependency

- physx/Cargo.toml
`cargo package` wasn't working on the `physx` crate as we only specified path-dependencies. 
Fixed it so we specify both path and version dependencies which is the standard way to handle this. It will use the path dependencies when building the repo and the version dependency when packaging and for the published crate.
> Fix internal dependencies for packaging + remove floating-duration

- .gitignore
- physx-sys/Cargo.toml
- physx-sys/build.rs
- physx/Cargo.toml
When `build.rs` was running on Windows with MSVC the structgen.cpp file generated a structgen.obj directly in physx-sys directory during the build which fails cargo packaging & publishing.
Now I force MSVC to put object file outputs in the output path.
Also bumped the crate versions because the previous version I had published included the structgen.obj file in the crate (!) which failed to build when syncing it down because Cargo stored it (correctly) as read-only.  So I had to yank those previously published releases today.
Kinda messy situation but glad to have found a simple solution for it, this is something that was an issue from the beginning (see #13) but think it only failed packaging/publishing correctly on Windows.
> Fix Windows issue with generated structgen.obj file

- physx/Cargo.toml
- physx/src/actor.rs
- physx/src/articulation_cache.rs
- physx/src/base.rs
- physx/src/foundation.rs
- physx/src/heightfield.rs
- physx/src/rigid_body.rs
- physx/src/scene.rs
- physx/src/shape.rs
- physx/src/visual_debugger.rs
This drops a transitive dependency on pre-1.0 `syn`, which
should improve compile times.
I wasn't able to compile the `-sys` crate locally, so I'm going to make use of your CI :)
> Update enumflags2 to 0.6

- physx/Cargo.toml
- physx/src/math/mod.rs
- physx/src/rigid_actor.rs
0.8 includes two `glam` fixes/changes that we filed and @bitshifter implemented:
- https://github.com/bitshifter/glam-rs/issues/22
- https://github.com/bitshifter/glam-rs/issues/21
Bumped the minor verison of `physx` here as we use `glam` in the public API of the crate
> Upgrade glam 0.7 -> 0.8

- README.md
- physx-sys/Cargo.toml
- physx-sys/build.rs
- physx/Cargo.toml
- physx/README.md
- physx/examples/ball_physx.rs
- physx/src/lib.rs
Upgrade to latest available version of PhysX, 4.1.1.27006925.
Will publish this release and then do a follow up patch release that switches it to use our fork of 4.1.1 that fixes Xcode 11 support (https://github.com/NVIDIAGameWorks/PhysX/pull/185) for #23
> Upgrade to PhysX 4.1.1

- .github/workflows/ci.yaml
- .gitmodules
- README.md
- physx-sys/Cargo.toml
- physx-sys/build.rs
- physx/Cargo.toml
- physx/README.md
- physx/examples/ball_physx.rs
- physx/src/lib.rs
This temporary switches to use PR & fork of PhysX 4.1.1 that fixes compilation on Xcode 11:
https://github.com/NVIDIAGameWorks/PhysX/pull/185
Fix #23
> Fix Xcode 11 support with 4.1.1

- .github/workflows/ci.yaml
- physx-sys/Cargo.toml
- physx-sys/build.rs
Fixes #35 and missing typeinfo.h issues with Visual Studio 2019.
The linker error was caused by the wrong directory being used for build static libs. It is now discovered automatically by the `build.rs` script.
The PhysX submodule is updated to point to our fork which now includes a workaround for the missing include file.
Includes Visual Studio 2019 CI build config from #36.
> Fix build issues with vs2019

- physx-sys/build.rs
PxConfig.h is generated in the source directories by PhysX's build system. This upsets cargo, so let's just delete the file after the build is done.
> Fix cargo publish by removing PxConfig.h at the end of build.rs

- physx/src/articulation_reduced_coordinate.rs
- physx/src/cooking.rs
- physx/src/geometry.rs
* Using PxVec3 in triangle meshes, so the sizes match up
Previously this used glam's Vec3, which does not always match the size of Physx's PxVec3. 
* Added mesh scale as an argument to `create_triange_mesh`
* Fixed validation being checked backwards
> Using PxVec3 in triangle meshes, so the sizes match up

- physx-sys/Cargo.toml
- physx/Cargo.toml
Should we squash?
Had to make the last commit myself.
> Release physx 0.5.0 and physx-sys 0.3.0

- physx/Cargo.toml
There was a flag --no-dev-version to cargo release to avoid that awkward version bump.
> (cargo-release) version 0.5.1

- physx-sys/Cargo.toml
- physx-sys/build.rs
Nice to not bring in the `cmake` crate at all by default! 
You're welcome @Jake-Shadle :)
> Only bring in cmake crate if `use-cmake` is enabled

- physx-sys/CHANGELOG.md
- physx-sys/Cargo.toml
- physx/CHANGELOG.md
- physx/Cargo.toml
Biggest thing this includes is #59 and #60.
Made this not a patch version release, as although those changes are compatible they are fairly major in the build system so better for users to choose to upgrade to them manually with a version change.
> Release physx 0.6.0 and physx-sys 0.4.0

- physx-sys/cc.rs
* Uses new commits on upstream physx code to fix a few warnings
* Disables some warnings that are just tedious to fix in C++ code
> Fix clang 10.0.0 warnings

- README.md
- physx-sys/cc.rs
Also adds a note about MSVC's poor behavior when compiling in release with debug info and provides a workaround.
Resolves: #65
> Fixup build script

- physx-sys/src/lib.rs
- physx-sys/src/physx_api.cpp
With this, you can register a callback to use to decide what objects can be hit by raycasts. In the callback, you get the actor, the custom filterdata for the mesh, and a userdata pointer. To reject a single object for example, pass in the PxActor through userdata and compare.
> Add the ability to register a raycast filter callback from Rust

- .github/workflows/ci.yaml
- physx-sys/cc.rs
- physx-sys/pxbind/run_android.sh
Building structgen using `cargo build` still needs to be fixed. Right now I'm using `run_android.sh` for that instead.
#68
> Android CI and renamed NDK_HOME

- .github/workflows/ci.yaml
It's currently broken in the "build and run pxbind" step with the following output:
```
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LLVM 6.0.0
-- Using LLVMConfig.cmake in: /usr/lib/llvm-6.0/cmake
-- LLVM_LIBS: LLVMX86AsmParser;LLVMBitReader;LLVMSupport;LLVMMC;LLVMOption;LLVMProfileData
bash: llvm-config: command not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/runner/work/physx-rs/physx-rs/physx-sys/pxbind/build
Scanning dependencies of target pxbind …
```
> Disable the Android structgen CI target

- physx-sys/CHANGELOG.md
- physx-sys/Cargo.toml
- physx-sys/src/lib.rs
- physx-sys/src/physx_api.cpp
- physx/CHANGELOG.md
- physx/src/physics.rs
- physx/src/scene.rs
Now supporting registering all six types, not just collision. Needed for trigger shapes.
Preserves, and deprecates, the old interface.
> New interface for registering simulation event callbacks

- physx-sys/CHANGELOG.md
- physx-sys/Cargo.toml
- physx/CHANGELOG.md
- physx/Cargo.toml
@hrydgard looks like you deprecated `set_simulation_event_callback` also in #80, can you add that to the CHANGELOG also. I guess technically we should do a minor release rather than a patch release if it has deprecations, but think this is fine as we are pre 1.0
> Release physx 0.7.1 and physx-sys 0.4.9

- physx-sys/README.md
- physx-sys/src/lib.rs
- physx-sys/src/physx_api.cpp
- physx/src/foundation.rs
This lets the user handle or track allocations as they please.
> Allow overriding the PxAllocatorCallback with a pair of custom callback functions

- physx-sys/CHANGELOG.md
- physx-sys/Cargo.toml
- physx/CHANGELOG.md
- physx/Cargo.toml
As it says on the tin.
Adds the ability to override the memory allocator.
> Release physx 0.7.4 and physx-sys 0.4.10

- README.md
- physx-macros/README.md
- physx-sys/README.md
- physx/README.md
Looks quite nice and likely should have both on all of our Rust crates.
https://deps.rs recently got revived and has new mantainers, and our Ark Discord is pretty new also
> Add deps.rs and Ark Discord badges

- .github/workflows/ci.yaml
First tried Xcode 12 but got build errors, so switched to latest Xcode 11.7 for now instead
> Use Xcode 11.7 on Mac CI

- physx-sys/cc.rs
- physx/src/controller.rs
- physx/src/math/mod.rs
- physx/src/physics.rs
- physx/src/transform.rs
One error is caused by a missing argument to panic!.
The others seem to be related to the recent glam upgrade.
> Fix warnings found by clippy

- physx/Cargo.toml
I'd like a new release so physx is compatible with glam version that have have fully deprecated `.x()` and etc in favor of `.x`
> Release physx 0.8.1

- README.md
- physx/CHANGELOG.md
- physx/README.md
- physx/examples/ball_physx.rs
- physx/src/convex_mesh.rs
- physx/src/math/mod.rs
- physx/src/physics.rs
- physx/src/prelude.rs
- physx/src/scene.rs
- physx/src/traits/descriptor.rs
- physx/src/traits/mod.rs
- physx/src/triangle_mesh.rs
First round of changes. Will require a major API version bump once it's all in.
Generally this wasn't too bad but there are holes.
A lot of the SceneDesc parameters were lost, added back a few. It's gonna be more though, so should we add a builder?
Now includes @Hentropy 's new object creation rework.
> Fix issues I ran into when porting our code to the new API

- physx/src/cooking.rs
This change makes triangle mesh validation optional, allowing for potential performance improvements when the mesh has already been validated. The API user is still responsible for validating their mesh.
I've replaced the mesh validation with mesh descriptor validation.
> Make convex and triangle mesh validation optional

- physx/CHANGELOG.md
Want to be able to use the latest changes, so even if there's stuff pending, let's make a release. Version numbers are free.
Only the high-level API has changes, physx-sys is not touched.
- [PR#113](https://github.com/EmbarkStudios/physx-rs/pull/98) Fix various issues found using physx-rs in practice after the big PR#98 merge from 0.9.0.  You now create a scene using `Physics::create()` with a new scene descriptor that can represent all the parameters of PxSceneDesc.
- [PR#120](https://github.com/EmbarkStudios/physx-rs/pull/120) Make convex and triangle mesh validation optional.
> Release Physx 0.10.0

- physx-sys/build.rs
- physx-sys/src/generated/aarch64-apple-darwin/structgen.rs
- physx-sys/src/generated/aarch64-apple-darwin/structgen_out.hpp
- physx-sys/src/lib.rs
Adds initial support for Mac M1 ARM CPUs.
This may not be correct as had problems running our pxbind structgen utility on Mac M1 so for now just copy'n'pasted the x86_64 Mac structgen files. Does seem to run but could be subtle differences (that could cause catastrophic failures)?
Resolves: #92
> Initial aarch64-apple-darwin support

- physx/CHANGELOG.md
- physx/Cargo.toml
- physx/src/math/glam.rs
- physx/src/math/mod.rs
- physx/src/math/quat.rs
- physx/src/math/transform.rs
- physx/src/math/vec3.rs
Currently upgrading rust-gpu in Ark is usually blocked on physx-rs because Ark disallows duplicate deps and glam's minor version number changes often. This PR changes it so `glam` is optional dependency of `physx`, which should allow Ark to not depend on `glam` from `physx`.
> Make glam an optional dependency

- physx-sys/CHANGELOG.md
Just applies this simple fix, where inlining could cause bad intrinsics usage on a path that could not be taken (the function was called with index=2, which is not a valid parameter for that intrinsic).
https://github.com/EmbarkStudios/PhysX/commit/dc5059fb1acbf6a710c50f538b727a851c2d1139
> Update PhysX submodule with ARM64 buildfix for Xcode 14.5

- .github/workflows/ci.yaml
- LICENSE-MIT
- README.md
- deny.toml
- physx-sys/CHANGELOG.md
- physx-sys/Cargo.toml
- physx-sys/LICENSE
- physx-sys/LICENSE-APACHE
- physx-sys/LICENSE-BSD
- physx-sys/LICENSE-MIT
- physx-sys/README.md
- physx-sys/src/lib.rs
- physx/LICENSE-APACHE
- physx/LICENSE-MIT
- physx/src/foundation.rs
- physx/src/lib.rs
- The MIT license was missing the Embark Studios copyright
- The physx-sys crate wasn't packaging the license files since they weren't in the crate root, so just copied them there
- Added the BSD-3-Clause license text from PhysX into the root as well
- Fixed the license expression for the -sys crate to `(MIT OR Apache-2.0) AND BSD-3-Clause` as the Rust code is licensed under MIT OR Apache-2.0, but the C++ code is under the BSD-3-Clause
- Updated README to fix various issues and just generally spruce it up
> Fixup licenses

- physx/Cargo.toml
- physx/src/math/mod.rs
The version of glam is quite outdated (~11 mo), and makes it difficult to use conversions for those that use the optional "glam" feature.
> Upgrade glam from 0.13 to 0.20 (optional dependency)

- physx-sys/release.toml
- physx/release.toml
These were preventing cargo release from running.
> Remove outdated fields from release.toml files

- physx/CHANGELOG.md
- physx/Cargo.toml
Last step of the automated `cargo release` failed because we have protected branch main.
So let's get it in this way instead. Please make sure to squash-merge.
> Release physx v0.12.2

- physx-sys/README.md
- physx-sys/pxbind/CMakeLists.txt
- physx-sys/pxbind/main.cpp
- physx-sys/src/generated/x86_64-apple-darwin/structgen.rs
- physx-sys/src/generated/x86_64-apple-darwin/structgen_out.hpp
- physx-sys/src/generated/x86_64-pc-windows-msvc/structgen.rs
- physx-sys/src/generated/x86_64-pc-windows-msvc/structgen_out.hpp
- physx-sys/src/generated/x86_64-unknown-linux/structgen.rs
- physx-sys/src/generated/x86_64-unknown-linux/structgen_out.hpp
- physx-sys/src/physx_generated.hpp
- physx-sys/src/physx_generated.rs
- physx-sys/src/structgen/structgen.cpp
- physx/src/rigid_dynamic.rs
This makes it a bit easier to add new targets since it's possible to use newer clang/llvm libs. Also updated documentation.
However it seems some of the generated bindings got some new types (did they not the currently checked in Physx version?) which causes some problems since I have some trouble re-generating all the platform specific bindings. I can do it for my own platform ofc but would be nice with some help for the rest of the platforms.
> Update supported clang/llvm for pxbind

- .github/workflows/ci.yaml
- physx-sys/build.rs
- physx-sys/pxbind/run-aarch64-linux.sh
- physx-sys/src/generated/aarch64-unknown-linux-gnu/structgen.rs
- physx-sys/src/generated/aarch64-unknown-linux-gnu/structgen_out.hpp
- physx-sys/src/lib.rs
Tested on Ampere Altra Arm64. Added extra run script since we already have a separate for android (this needs `-fsigned-char`) and didn't want to over compilcate the bash scripts
follow up of: https://github.com/EmbarkStudios/physx-rs/pull/153
> Add aarch64-unknown-linux-gnu support

- physx-sys/CHANGELOG.md
- physx-sys/src/lib.rs
- physx-sys/src/physx_api.cpp
- physx/CHANGELOG.md
- physx/examples/error_callback.rs
- physx/src/foundation.rs
- physx/src/physics.rs
- physx/src/physics/error_callback.rs
A slight modification to make it work a bit more like your original proposal; while still keeping the trait pattern we have. Also avoids the sized-ness/boxing issue we've seen before.
Not sure why the char types were *const c_void; we try to keep them as signed chars in the interface as it's most consistent.
> Trait + early conversion for error callback

- physx-sys/CHANGELOG.md
- physx-sys/examples/ball.rs
- physx-sys/src/lib.rs
- physx-sys/src/physx_api.cpp
This just lifts the physx-sys part of #119, so that even if it's not exposed in physx-rs it can at least be accessed through the low-level api.
> Add scene query support to physx-sys

- physx-sys/CHANGELOG.md
- physx-sys/Cargo.toml
- physx/CHANGELOG.md
- physx/Cargo.toml
Released both as physx had some lint fixes.
ACTUALLY shouldn't merge this as the bot will squash and break the tags...
> Release physx-sys and physx

- physx-sys/build.rs
The `PxPhysicsVersion.h` file moved (both because we changed the submodule checkout location, but also because of an upstream change), and instead of giving a warning that the file didn't exist, cargo just...rebuilt the physx-sys build code every time.
> Fix unnecessary recompiles

- deny.toml
- physx-sys/CHANGELOG.md
- physx-sys/pxbind/Cargo.toml
- physx-sys/src/lib.rs
- physx-sys/src/physx_api.cpp
Implements a C++ trampoline and Rust interface for setting both pre and post filters.
> Add support for post filter

- physx-sys/CHANGELOG.md
- physx-sys/Cargo.toml
- physx/Cargo.toml
Here we go again. 0.11.2 was broken on `crates.io`, most likely due to my repo being broken.
> Release `physx-sys` 0.11.3

- physx-sys/CHANGELOG.md
- physx-sys/src/lib.rs
This enables building for `x86_64-linux-android` targets, which is particularly useful for running under an Android emulator.
For reference here I first explicitly ran `structgen` (built for x86_64-linux-android to with the latest r25 Android NDK toolchain) on an Android emulator and compared the output to the existing `generated/unix/` code, which was identical.
This was how I double checked the output of structgen cross-compiled for x86_64-android-linux on an Android emulator:
```bash
export ANDROID_API_LEVEL=31
export ANDROID_ARCH=x86_64 # | i686
export ANDROID_ABI=x86_64 # | x86
export HOST_OS=linux # | windows
export EXT="" # | .bat
"$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/$HOST_OS-x86_64/bin/clang++" \
-DANDROID \
--target=$ANDROID_ARCH-linux-android$ANDROID_API_LEVEL \ …
```
> Build for x86_64-linux-android with generated/unix/ code

- physx-sys/pxbind/src/consumer.rs
- physx-sys/pxbind/src/consumer/enums.rs
- physx-sys/pxbind/src/consumer/record.rs
- physx/CHANGELOG.md
- physx/src/traits/user_data.rs
see discussion in https://github.com/EmbarkStudios/physx-rs/issues/210
I've also added a test, which verifies userdata storing/retrieving with various types, and may also reproduce a problem with older code. You can run it with the following command:
```sh
cargo test --package physx --lib -- traits::user_data::tests --nocapture
```
line 28 is where the bug is at, lines 24-25 are changed only for consistency reasons
> Fix misaligned pointer dereference when storing UserData

- physx/src/convex_mesh.rs
- physx/src/height_field.rs
- physx/src/triangle_mesh.rs
I'm working on physx-bevy integration [plugin](https://github.com/rlidwka/bevy_physx), and I need tools to visualize all shapes on the screen for debugging purposes. Using physx-sys API quickly turned into nightmare with pointers, so I wrote API to abstract all that.
This PR is relatively straightforward porting of all methods in [PxTriangleMesh](https://nvidia-omniverse.github.io/PhysX/physx/5.1.3/_build/physx/latest/class_px_triangle_mesh.html), [PxHeightField](https://nvidia-omniverse.github.io/PhysX/physx/5.1.3/_build/physx/latest/class_px_height_field.html) and [PxConvexMesh](https://nvidia-omniverse.github.io/PhysX/physx/5.1.3/_build/physx/latest/file_include_geometry_PxConvexMesh.h.html) classes (with the exception of new SDFs getters from physx 5.1, which I didn't get around to).
> high-level API for ConvexMesh, TriangleMesh, HeightField

- physx-sys/CHANGELOG.md
- physx-sys/build.rs
A lot of undefined behavior with all the reinterpret_cast usage in physx.
The following was broken compiling without `-fno-strict-aliasing` with clang/llvm 16:
https://github.com/NVIDIA-Omniverse/PhysX/blob/main/physx/source/geomutils/src/intersection/GuIntersectionRayBox.cpp#L199
> Use -fno-strict-aliasing when building physx

- Cargo.toml
- physx/src/material.rs
- physx/src/shape.rs
- physx/tests/bug-180.rs
Fixes #180
@rlidwka  Correct analysis indeed, Physx internally decrements the ref count so no need for our wrappers to do so -- that leads to decrementing the ref-count twice. Do you have a bigger context where you'd be able to try this and ensure it now works?
> Do not manually free materials for shapes

- physx-sys/pxbind/src/dump.rs
Fixes the build error seen in https://github.com/EmbarkStudios/physx-rs/actions/runs/6461599287/job/17541604297?pr=216
> chore: Fix clippy lint from 1.73

- physx-sys/CHANGELOG.md
- physx-sys/build.rs
The NDK puts universal binaries under the `darwin-x86_64` directory.
Verified that it works by patching Cargo.toml to use this branch while building on an M1 macbook.
> Support building for Android on aarch64 macOS hosts

- physx/examples/ball_physx.rs
- physx/examples/profiler.rs
This fixes the examples that break if run in debug mode in more recent rust versions.
> Fix misalignment in examples

- .github/CODEOWNERS
Since I don't actually do much with physx/ics we've talked about having @blunzn and @bpaberg take over maintainership of this repository in the long term.
> Add Peter and Peter as CODEOWNERS
