EmbarkStudios/physx-rs

.github/workflows/ci.yaml
To verify the complex build.rs steps work properly for all platforms and on all changes
=> Add CI step to package physx-sys crate

physx-sys/build.rs, physx/src/physics.rs, physx/src/scene.rs, physx/src/transform.rs
=> [cmake] Support building for static CRT. Also fix minor glam warning.

physx/Cargo.toml, physx/src/controller.rs, physx/src/lib.rs, physx/src/physics.rs, physx/src/prelude.rs, physx/src/scene.rs
Started to expose some character controller functionality.
Not all the functionality is exposed yet, just enough to create and move a capsule controller.
=> Character controller

physx/src/physics.rs, physx/src/scene.rs
This was the easiest way to get it back.
=> We're gonna need create_scene_raw for a bit longer.

physx/src/scene.rs
Wanted to see if this flag can help with an issue we have.
=> Scene: Add support for enabling CCD, which can help with tunneling.

physx-sys/build.rs, physx-sys/cc.rs
And by fix I mean just ignore warnings until it stops complaining.
Resolves: #63
=> Fix compiling with g++

physx-sys/CHANGELOG.md, physx-sys/Cargo.toml
Reduces size of the .crate from 10 MB to 2.7 MB!
=> Remove unused files in sys crate to reduce size

physx-sys/CHANGELOG.md, physx-sys/Cargo.toml, physx/CHANGELOG.md, physx/Cargo.toml
=> Release physx 0.6.1 and physx-sys 0.4.3

physx/CHANGELOG.md, physx/Cargo.toml, physx/src/math/mod.rs
Replaces #71 .
Before we merge this, I'll patch my local ark to use this and test that it works.
=> Upgrade glam to 0.9

physx-sys/cc.rs
It was hardcoded to `linux-x86_6`, so here detect which target the host is to pick the right toolchain for Windows and Mac.
Also manually verify that the sysroot path for the target actually exists as clang will just ignore it if it doesn't exist, and then you'll get "fun" compile errors instead
=> Fix Android NDK toolchain path selection on Mac & Windows

physx-sys/CHANGELOG.md
Dummy PR to check CI on main, really.
=> Add missing lint to CHANGELOG.

physx-sys/CHANGELOG.md, physx/CHANGELOG.md, physx/Cargo.toml
Only physx has changes, so not updating physx-sys.
=> Release physx 0.7.2

physx/src/scene.rs
=> Expose a bunch of additional parameters on SceneBuilder

README.md, physx/CHANGELOG.md, physx/Cargo.toml
Only physx has changes, so not updating physx-sys.
=> Release physx 0.7.3

physx/Cargo.toml, physx/src/math/mod.rs
Tiny single change in our code, will do a release after this
=> Upgrade glam v0.9 -> v0.10

physx/Cargo.toml
Followup to https://github.com/EmbarkStudios/physx-rs/pull/121
=> Forgot updating the version, oops.

physx/CHANGELOG.md, physx/Cargo.toml
=> Release physx 0.11.0

physx-sys/CHANGELOG.md, physx-sys/Cargo.toml
Fixes a build issue with XCode 14.5 on ARM64.
Not changing physx at this time.
=> Release physx-sys 0.4.13

README.md, physx-sys/CHANGELOG.md, physx-sys/release.toml, physx/CHANGELOG.md, physx/release.toml
- Fix link
- Update physx-sys CHANGELOG
- Add cargo-release support to physx-sys
- Cleanup CHANGELOG
- Add cargo-release support to physx
- Update README for how to use cargo-release
- Update CHANGELOG
=> Prep release

physx-sys/src/lib.rs, physx/src/base.rs, physx/src/lib.rs, physx/src/material.rs, physx/src/rigid_dynamic.rs, physx/src/scene.rs
Found multiple errors when updating to clang-13 due to variables being set but never actually read.
=> Fix clang-13 errors

physx-sys/build.rs, physx-sys/src/generated/aarch64-linux-android/structgen.rs, physx-sys/src/generated/aarch64-linux-android/structgen_out.hpp
Also improves build script slightly to make it easier to do these kinds of updates in the future
=> Update android generated code

physx-sys/CHANGELOG.md, physx-sys/Cargo.toml, physx-sys/build.rs, physx-sys/src/lib.rs, physx-sys/src/physx_api.cpp, physx/CHANGELOG.md, physx/examples/profiler.rs, physx/src/foundation.rs, physx/src/physics.rs, physx/src/physics/profiler.rs, physx/src/simulation_event_callback.rs
=> Add support for setting PhysX profiler

physx/CHANGELOG.md, physx/src/visual_debugger.rs
Tested locally and it connects for me now.
=> keep oshost alive in connection

physx-sys/CHANGELOG.md
Will do a release of physx-sys after this.
=> missing heading

README.md, physx-sys/README.md
=> Update PhysX links to Nvidia omniverse PhysX 5's ones

physx-sys/CHANGELOG.md, physx-sys/Cargo.toml, physx/Cargo.toml
=> Release `physx-sys` 0.11.2

physx/CHANGELOG.md, physx/src/actor.rs, physx/src/scene.rs
see discussion in https://github.com/EmbarkStudios/physx-rs/issues/205
=> Add immutable API for ActorMap
